### ISSUE TITLE
Tracking: Add basic donation support to flathub frontend

### ISSUE THREAD

**Issue by danielsilverstone-ct** [flathub/website#14]
To support the basic donation support outlined in flathub/website#36 we need the following frontend work doing:

* [x] Add basic wallet (cards) and transactions/orders page to user info
* [x] Support retrieving keys and constructing Stripe objects lazily
* [x] Add flow for completing a `new` or `retry` status transaction
* [x] Come up with a basic "Make a donation to Flathub" UI
* [x] Deploy this to beta

**Comment by kymckay** [comment]
All tasks here are complete. Please reopen if you think this isn't done.
