### ISSUE TITLE
Tracking: Donations and payments - WP4

### ISSUE THREAD

**Issue by danielsilverstone-ct** [flathub/website#256]
Stuff moved from WP3 around payments and donations

- [ ] Backend support to generate tokens to permit users to be gifted ownership of an app
- [ ] Frontend support for creating and redeeming such tokens
- [ ] The flatpak-authenticator-app workflow needs to be integrated with the workflows
- [ ] Determine tax management approach and implement product upsert and invoice management in stripe backend
- [ ] Frontend support to show ownership information to users
- [ ] Finalised frontend support for defining payment/donation levels

**Comment by Jamespric** [comment]
@danielsilverstone-ct  does this list cover the items mentioned previously in #166 ?
@ramcq Are you happy with this definition for WP4?
