### ISSUE TITLE
Tracking: Add basic donation support to flathub backend

### ISSUE THREAD

**Issue by danielsilverstone-ct** [flathub/website#36]
We have considered what's sensible and decided that the initial donation support for the flathub website will be permitting US dollar donations to Flathub itself.  This is the least likely to be problematic with tax and so should allow us to iron out the Stripe flows etc. ready for when we want to widen the net.

* [x] Implement core Wallet API and FakeWallet including a fake webhook
* [x] flathub/website#33 
* [x] Organise an official Flathub Stripe account
* [x] Deploy to beta with official account **test** keys
* [x] Validate in "beta"
