### ISSUE TITLE
Tracking: Add support for app authors to set donation/payments up

### ISSUE THREAD

**Issue by danielsilverstone-ct** [flathub/website#93]
In order for app authors to set up donations/payments we need:

- [x] Backend support for onboarding a Stripe Express Account, including dashboard access
- [x] Frontend support for that flow
- [x] Backend support for defining payment/donation levels and creating transactions based on them
- [x] Rudimentary frontend support for defining payment/donation levels for applications
- [x] Backend support for noticing when a transaction completes for a payment and logging ownership

**Comment by danielsilverstone-ct** [comment]
@ramcq @JamesPrice76 I think that's the bare minimum to meet our agreed goal of supporting an end-to-end of "I has an app, allow donations pls, yay I donate, hurrah moneys happened" and similarly for purchases.  Do you agree?

**Comment by danielsilverstone-ct** [comment]
Items migrated from WP3 to WP4 are tracked here: https://github.com/flathub/website/issues/256

**Comment by Jamespric** [comment]
@ramcq do you think this list covers WP3?

**Comment by danielsilverstone-ct** [comment]
With the merge of #353 this is now done.  Work proceeds to WP4.

**Comment by datpaitoon17** [comment]
> In order for app authors to set up donations/payments we need:
> 
> - [x] Backend support for onboarding a Stripe Express Account, including dashboard access
> - [x] Frontend support for that flow
> - [x] Backend support for defining payment/donation levels and creating transactions based on them
> - [x] Rudimentary frontend support for defining payment/donation levels for applications
> - [x] Backend support for noticing when a transaction completes for a payment and logging ownership
>
